### ISSUE TITLE
Data pre-processing problem

### ISSUE THREAD

**Issue by FeiiYin** [NVlabs/eg3d#16]
Hi, Thanks for your impressive work!

I have a problem with the data processing.
We will align and re-crop the wild FFHQ dataset in the data pre-processing script.
I wonder about the difference between the current re-crop procedure and the origin FFHQ crop procedure.
Can we achieve the same processed dataset within the cropped FFHQ dataset via directly predicting its camera coefficients, since the FFHQ-wild is too large?

Thanks in advance!

**Comment by ericryanchan** [comment]
Hi FeiiYin,

The reason we recropped the in-the-wild images was because it was easier to ensure our detected camera poses were properly aligned with the images. However, if you can predict the camera coefficients directly on the original crop, it should work just fine! We did a preliminary experiment with the original crop a while ago and it was approximately on par with our recropped images, so I don't think the specific crop makes too much of a difference.

**Comment by FeiiYin** [comment]
Thanks for your instant reply!
