### ISSUE TITLE
ffhq data download

### ISSUE THREAD

**Issue by liushanyuan18** [NVlabs/eg3d#34]
thank you for your excellent work!
I'm reproducing the ffhq experiment,but in-the-wild-images is too large,and i can't understand the code in 'runme.py'.Could you please provide the zip of ffhq that eg3d can use directly?

**Comment by ericryanchan** [comment]
Hi Liushanyuan, email me directly and I'll help you get the data set up :)

**Comment by luminohope** [comment]
Please also refer to the original FFHQ repo for any relevant issues : https://github.com/NVlabs/ffhq-dataset
Our script downloads the original data from that repo and the problem is not specific to our script.

**Comment by yesheng-THU** [comment]
Hi Eric, can you please tell me what your email address is? Thanks a lot

**Comment by zhouwy19** [comment]
Can anyone send the dataset to me: 576825820@qq.com？Thank you！

**Comment by povolann** [comment]
For all the people who have problems to download the dataset, I was following this: https://github.com/NVlabs/ffhq-dataset/pull/3 (don't forget to change/download the new `download_ffhq.py` file so you can use the `--pydrive` and `--cmd_auth` flags) and then I changed the line
`cmd = "python download_ffhq.py --wilds"`
for
`cmd = "python3 download_ffhq.py -i --pydrive --cmd_auth"`
 in `runme.py` file (depends on you if you want to keep the `-i` flag or `--wilds` flag).

**Comment by auroraxs** [comment]
can someone send a dataset to me ? My email is xusensuncv@gmail.com
Thank you very much

**Comment by szh-bash** [comment]
Please someone send the preprocessed data to x799927254@gmail.com, thanks a lot!
Especially 'FFHQ_512.zip'!

**Comment by cwchenwang** [comment]
@povolann can you provide more details in how to setup the google api to use pydrive? I cannot find a way to generate my client_secrets.json.

**Comment by povolann** [comment]
> @povolann can you provide more details in how to setup the google api to use pydrive? I cannot find a way to generate my client_secrets.json.

Sorry for not getting back to you sooner, but I needed a bit more time to go through the process. It was a lot of debugging since I didn't remember from last time :D So, this is how I did it.
I have followed these:
https://github.com/NVlabs/ffhq-dataset/pull/3
https://pythonhosted.org/PyDrive/quickstart.html#authentication - how to set up the API to use pydrive
So, the instructions are pretty clear for me to follow, where it wasn't very clear are points 3. and 4.

> 3. Select ‘Credentials’ from the left menu, click ‘Create Credentials’, select ‘OAuth client ID’.
> 4. Now, the product name and consent screen need to be set -> click ‘Configure consent screen’ and follow the instructions.

I have just filled out the mandatory stuff for the OAuth consent screen, but at first, I didn't add any Test users - it will lead to denying your authentication later, so add your Gmail account here. But if you go back to Credentials after this, there is still no OAuth client ID. So, you have to do step 3 again. Then you will get to

> a. Select ‘Application type’ to be Web application.

Actually, I have tried Google Authentication with Web application (didn't work for me because of mismatching URIs) and the Desktop application worked for me. But otherwise, I have followed the instruction.
After that, I got this screen (there's still the Web version, but you get the idea):
![image](https://github.com/NVlabs/eg3d/assets/31487206/0eec5755-720b-42eb-93d9-c1c6421799c9)

Also, keep in mind that I have used the adjusted file for downloading the images from [https://github.com/jeremyfix/ffhq-dataset/blob/pydrive/download_ffhq.py
](URL) The original file doesn't have the --pydrive --cmd_auth flags.

Pff, feel free to ask me if you have more questions.

**Comment by chenchao15** [comment]
can someone send a dataset to me ? My email is [thss15_chenc@163.com](mailto:thss15_chenc@163.com)
Thank you very much

**Comment by chence17** [comment]
Could someone also send the dataset to me? My email is [2955841829@qq.com](mailto:2955841829@qq.com)
Thank you very much

**Comment by 2680347338** [comment]
Could someone also send the dataset to me? My email is [2955841829@qq.com](mailto:2955841829@qq.com)
Thank you very much

**Comment by 2680347338** [comment]
Could someone also send the dataset to me? My email is [2680347338@qq.com](mailto:2680347338@qq.com)
Thank you very much

**Comment by ericryanchan** [comment]
For folks who need the preprocessed data, here's a drive link:
FFHQ:
https://drive.google.com/file/d/1XP0od0OM_pdPE6Cnv3joMYw7pIzHDEqo/view?usp=sharing

**Comment by johnren-code** [comment]
Hello, I would like to ask if your file link above contains the JSON file for the camera parameters?

**Comment by chence17** [comment]
I have uploaded the preprocessed FFHQ data to Baidu Netdisk (百度网盘) for researchers in China. This is the link:

Link (链接)：[https://pan.baidu.com/s/1t-feWfDOdgIS4r_JHRmp0g?pwd=1ute](https://pan.baidu.com/s/1t-feWfDOdgIS4r_JHRmp0g?pwd=1ute) 
Passcode (提取码)：1ute

**Comment by JiuTongBro** [comment]
> For folks who need the preprocessed data, here's a drive link: FFHQ: https://drive.google.com/file/d/1XP0od0OM_pdPE6Cnv3joMYw7pIzHDEqo/view?usp=sharing

Hi. Thanks for your sharing. I downloaded the ffhq dataset from this link. And visualized the GT images during the training. However, it seems there are many 'broken' images, like this one:
![D7Y75D1A6M%@$YT1XWF _ R](https://github.com/NVlabs/eg3d/assets/56216579/d6af2594-d31b-4e26-85a3-45f815c1c8bc)

I wonder is this caused by the original quality of FFHQ, or it is due to other reasons? Thanks!

**Comment by dwliu1412** [comment]
> I have uploaded the preprocessed FFHQ data to Baidu Netdisk (百度网盘) for researchers in China. This is the link:
> 
> Link (链接)：https://pan.baidu.com/s/1t-feWfDOdgIS4r_JHRmp0g?pwd=1ute Passcode (提取码)：1ute

Hi, thanks for your sharing.  I downloaded the ffhq dataset from this link, but there are only 139914 images in the folder instead of 140000images.
