### ISSUE TITLE
missing ffhq512-64.pkl in the pretrained model

### ISSUE THREAD

**Issue by jiaxinxie97** [NVlabs/eg3d#38]
Hi,

I download the eg3d_1.zip in the pretrained model link, but can not find the ffhq512-64.pkl in this folder

**Comment by matthew-a-chan** [comment]
Hi, can you provide a little bit more information about what's happening so we can diagnose this? 

1: What's in the 'eg3d_1.zip' folder? ie: source code? checkpoints? images?
2: Where/what link did you use to get this zip file?
3: Was it originally called 'eg3d_1.zip' or is that something you renamed it to when downloading? (I ask the last question because at the moment, I cannot recall any places where we uploaded a file with that name)

Let me know and hopefully we can get this resolved quickly. Thanks!

**Comment by jiaxinxie97** [comment]
Hi, 
1. the eg3d_1.zip is a pretrained model zip.
2. I download the zip from the webpage https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/eg3d using wget command wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/research/eg3d/versions/1/zip -O eg3d_1.zip.
3. The download cammand renamed it

**Comment by oneThousand1000** [comment]
> Ah I see. We don't actually distribute the `ffhq512-64.pkl` checkpoint (that is: the FFHQ checkpoint trained on 512x512px images tuned to 64^2 neural rendering).
> 
> Other options we do have: If you want a checkpoint trained on default unmodified FFHQ, you should use `ffhq512-128.pkl`. If runtime performance is crucial, you want a checkpoint tuned to 64^2 neural rendering so you should use `ffhqrebalanced512-64.pkl`. If neither of the above are particularly important, `ffhqrebalanced512-128.pkl` is a good all-around starting place for experiments and such.

Hi! I also want to know if there is any plan to release `ffhq512-64.pkl`.

I want to finetune the eg3d model at the low neural rendering resolutions of 64 on default unmodified FFHQ. `ffhqrebalanced512-64.pkl` does not work for me because its data distribution has changed a lot.

**Comment by luminohope** [comment]
Hi, for fine-tuning, ffhqrebalanced512-64.pkl or the other shouldn't make a big difference. For the purpose of transfer learning, you can even do fine-tuning for a wildly different dataset (please see StyleGAN2-ADA paper). Our AFHQ-Cat model is transferred learned from FFHQ as described in the paper.
