### ISSUE TITLE
About Geometry 

### ISSUE THREAD

**Issue by zhangqianhui** [NVlabs/eg3d#4]
hi guys

Which tools are used to visualize the geometry in this paper ?

**Comment by xieyipeng** [comment]
I have the same problem...

**Comment by MrTornado24** [comment]
I guess you can use ChimeraX as suggested in pi-gan.

**Comment by MrTornado24** [comment]
> 

I guess you can use ChimeraX as suggested in pi-gan.

**Comment by ericryanchan** [comment]
@MrTornado24 is correct! We used ChimeraX to generate most of the shape figures in the manuscript. It's really nice because you can explore the shapes in a GUI and adjust e.g. the levelset in real-time. Highly recommend it :)

Alternatively, you can use [marching cubes](https://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html) to extract the surface and use whatever mesh viewer you'd like.
