### ISSUE TITLE
Create meshes from my own images

### ISSUE THREAD

**Issue by Iana-Zhura** [NVlabs/eg3d#73]
Hello!
Can you please tell me how can I create the .mrc files from my own images? Should I change gen_samples.py code? Or I have to create my own dataset and train network ?

Thank you in advance!

**Comment by matthew-a-chan** [comment]
Hi, thanks for the question!
What do you mean by 'your own images'? Is this an image taken from your smartphone/camera or an image generated from the model?

If the latter, it's easy: just take the noise (z vector) or random seed used to generate the image and feed it to the gen_samples.py script (some slight modifications will be necessary if you want to input an exact z vector instead of a seed)
If the former, it's a bit more involved. You'll want to use some form of inversion to project your image into the latent space (ie: find a z that approximates your image closely) then use that instead. Do note that if the image is too crazy / diverges too much from the dataset, the approximation may not be very good. Issue #28 may be helpful for calculating the projection.

Good luck!

**Comment by Iana-Zhura** [comment]
yes, I mean the images that I have taken from my camera.
Thank you so much for your answer!
I have one more question. Have you ever tried to use your model on the images with several objects? I see in the artcile and in GitHub results only of images, which the focus on one object (human face or a car).

**Comment by matthew-a-chan** [comment]
Hi, Our method is built with specific design choices that optimize it for representing inward-facing, bounded, roughly central scenes. While this doesn't explicitly exclude scenes with multiple objects (for instance, a collection of pine cones on a table could be inward-facing, bounded, and central), most of the common datasets that we found (faces, cats, cars) tended to only have a single object.
